MyMusicStore/Controllers/ArtistsPageController.cs
using Microsoft.AspNetCore.Mvc;
using MyMusicStore.Domain.Interfaces;
using MyMusicStore.Domain.ViewModels;

namespace MyMusicStore.Controllers;

public class ArtistsPageController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public ArtistsPageController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<IActionResult> Index()
    {
        var artists = await _unitOfWork.Artists.GetAll();
        return View(artists);
    }

    public async Task<IActionResult> Albums(int id)
    {
        var artist = await _unitOfWork.Artists.GetById(id);
        var albums = await _unitOfWork.Artists.GetArtistsAlbums(id);

        var artistsPageViewModel = new ArtistsPageViewModel
        {
            Name = artist.Name,
            Image = artist.Image,
            Albums = albums
        };

        return View(artistsPageViewModel);
    }

    public async Task<IActionResult> Details(int? artistId, int? albumId)
    {
        var albums = await _unitOfWork.Artists.GetArtistsAlbums(artistId);
        var album = albums.FirstOrDefault(x => x.Id == albumId);
        if (album != null)
            album.Artist = await _unitOfWork.Artists.GetById(artistId);
        
        return View(album);
    }
}

MyMusicStore/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using MyMusicStore.Domain.Enums;
using MyMusicStore.Domain.Extensions;
using MyMusicStore.Domain.Interfaces;
using MyMusicStore.Domain.Models;

namespace MyMusicStore.Controllers;

public class CatalogController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public CatalogController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<IActionResult> Index(Genres genre)
    {
        List<Album> albums;
        if (genre > 0)
        {
            albums = await _unitOfWork.Albums.GetAlbumsByGenres(genre);
            ViewBag.Genre = genre.GetName();
        }
        else
        {
            albums = await _unitOfWork.Albums.GetAlbumsIncludeArtist();
            ViewBag.Genre = "Все альбомы";
        }

        ViewBag.Genres = genre.toList();
        return View(albums);
    }
}

MyMusicStore/Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyMusicStore.Domain.Interfaces;
using MyMusicStore.Domain.ViewModels;

namespace MyMusicStore.Controllers;

public class RolesController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public RolesController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
        return View(_unitOfWork.Roles.GetAll());
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(string name)
    {
        if (!string.IsNullOrEmpty(name))
        {
            var result = await _unitOfWork.Roles.CreateAsync(new IdentityRole(name));
            if (result.Succeeded)
                return RedirectToAction("Index");
            foreach (var error in result.Errors) ModelState.AddModelError(string.Empty, error.Description);
        }

        return View(name);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(string id)
    {
        var role = await _unitOfWork.Roles.FindById(id);
        await _unitOfWork.Roles.DeleteAsync(role);

        return RedirectToAction("Index");
    }

    public IActionResult UserList()
    {
        return View(_unitOfWork.User.GetAll());
    }

    public async Task<IActionResult> Edit(string userId)
    {
        var user = await _unitOfWork.User.GetById(userId);
        if (user != null)
        {
            var userRoles = await _unitOfWork.User.GetRolesAsync(user);
            var roles = _unitOfWork.Roles.GetAll();
            var model = new ChangeRoleViewModel
            {
                UserId = user.Id,
                UserEmail = user.Email,
                UserRoles = userRoles,
                AllRoles = roles
            };
            return View(model);
        }

        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> Edit(string userId, List<string> roles)
    {
        var user = await _unitOfWork.User.GetById(userId);
        if (user == null) 
            return NotFound();

        var userRoles = await _unitOfWork.User.GetRolesAsync(user);
        var addedRoles = roles.Except(userRoles);
        var removedRoles = userRoles.Except(roles);

        await _unitOfWork.User.AddToRolesAsync(user, addedRoles);

        await _unitOfWork.User.RemoveFromRolesAsync(user, removedRoles);

        return RedirectToAction("UserList");

    }
}

MyMusicStore/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyMusicStore.Domain.Helpers;
using MyMusicStore.Domain.Interfaces;
using MyMusicStore.Domain.Models;
using MyMusicStore.Domain.ViewModels;

namespace MyMusicStore.Controllers;

public class ShopCartController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public ShopCartController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
        var cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>("cart");
        var viewModel = new ShoppingCartViewModel
        {
            CartItems = cart,
            CartTotal = CartHelper.GetCartTotal(cart)
        };
        return View(viewModel);
    }

    public async Task<IActionResult> Buy(int id)
    {
        var album = await _unitOfWork.Albums.GetById(id);
        CartHelper.AddToCart(HttpContext.Session, album);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Remove(int id)
    {
        var album = await _unitOfWork.Albums.GetById(id);
        CartHelper.RemoveFromCart(HttpContext.Session, album);
        return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Checkout()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Checkout(Order order)
    {
        var cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>("cart");
        order.Total = CartHelper.GetCartTotal(cart);
        order.OrderDate = DateTime.Now;
        order.Email = User.Identity?.Name;
        await _unitOfWork.Orders.Create(order);
        await _unitOfWork.Orders.AddOrderItems(order.Id, cart);
        CartHelper.EmptyCart(HttpContext.Session);

        return RedirectToAction("Complete",
            new { id = order.Id });
    }

    [Authorize]
    public IActionResult Complete(int id)
    {
        var orders = _unitOfWork.Orders.GetAllOrders();
        var isValid = orders.Any(
            o => User.Identity != null &&
                 o.Id == id &&
                 o.Email == User.Identity.Name);

        if (isValid)
            return View(id);
        return View("Error");
    }
}

MyMusicStore/Views/Shared/_AlbumsList.cshtml
@model MyMusicStore.Domain.Models.Album
            <div class="col-lg-4 p-1">
            <div class="col">
          <div class="card shadow-sm">
           <img class="bd-placeholder-img card-img-top" src = @Model.Image>
            <div class="card-body">
              <h6 class="card-text">@Model.Title - @Model.Artist.Name</h6>
              <span class="badge bg-primary m-1">@Model.Price.ToString("c")</span>
              <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex pt-1">
                 <a  asp-controller="ArtistsPage" asp-action="Details" asp-route-ArtistId="@Model.ArtistId" asp-route-AlbumId="@Model.Id" class="btn btn-outline-secondary me-1 flex-grow-1">Перейти к альбому</a>
                 <a  asp-controller="ShopCart" asp-action="Buy" asp-route-id="@Model.Id" class="btn btn-outline-secondary me-1 flex-grow-1">Добавить в корзину</a>
                </div>
              </div>
            </div>
          </div>
        </div>
         </div>

MyMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyMusicStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MusicStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ArtistsPage" asp-action="Index">Артисты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Catalog" asp-action="Index">Каталог</a>
                        </li>
                        @if(User.IsInRole("Admin")){
                         <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="dropdown03" data-bs-toggle="dropdown" aria-expanded="false">
                                Управление
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                <li><a class="dropdown-item" asp-controller="AlbumsManager" asp-action="Index">Альбомы</a></li>
                                <li><a class="dropdown-item" asp-controller="ArtistManager" asp-action="Index">Артисты</a></li>
                                <li><a class="dropdown-item" asp-controller="Roles" asp-action="Index">Роли</a></li>
                            </ul>
                        </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ShopCart" asp-action="Index">Корзина</a>
                        </li>
                    </ul>
                     <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyMusicStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>